name: nrel-ai
channels:
  - default
  - conda-forge

dependencies:
  - python<=3.11
  - jupyterlab
  - pip>=20.3
  - pip:
    - git+https://github.com/NREL/tf-melt.git
    - matplotlib
    - scikit-learn
    - jupyter_contrib_nbextensions
    - black
    - isort
    - flake8
    - sphinx