name: nrel-ai
channels:
  - conda-forge
  - default
  - pytorch

dependencies:
  - python<=3.11
  - jupyter
  - pip>=20.3
  - pip:
      - git+https://github.com/NREL/tf-melt.git
      - git+https://github.com/NREL/pt-melt.git
      # - torch
      # - torchvision
      - torchinfo
      - matplotlib
      - scikit-learn
      # - jupyter_contrib_nbextensions
      - black
      - isort
      - flake8
      - sphinx
      - ray[data,train,tune,serve]
